### ISSUE TITLE
Skip transformation

### ISSUE THREAD

**Issue by niksy** [postcss/postcss-focus#1]
Is there any way of skipping transformation for particular selectors (e.g. you only want to have `:hover` styles)?

**Comment by ai** [comment]
Yeap, I think skipping will be useful. But what API we should use?

```css
input:only-hover {}
```

```css
/* postcss-focus: disable */
input:only-hover {}
```

What do you think?

**Comment by niksy** [comment]
`:only-hover` sounds nice, didn’t think of that! But, following currently available pseudo selectors, maybe parsing something like `:hover:not(:focus)` could produce only `:hover` styles? Or is this something too complicated?

**Comment by ai** [comment]
@niksy `:hover:not(:focus)` is awesome idea!

Do you want to make a PR? (I will be able to fix it only in Wednesday)

**Comment by niksy** [comment]
@ai looking at it more closely, `:hover:not(:focus)` maybe doesn’t represent something which will produce desired output—it just isn’t clear enough, it means that hover styles should be applied only when focus is not active. `:only-hover` probably gives more expecting end result.

I had similar idea for this plugin some time ago and was delighted to see you created something like that. My idea was to create new pseudo selector, `:fover` (as in focus+hover) which will do this, and could also remove outline as described in #2. Is going the route of new pseudo selector something you would consider?

**Comment by ai** [comment]
@niksy `postcss-fover` is a nice solution too. We can crosslink each other.

**Comment by niksy** [comment]
@ai There is a new PostCSS plugin which does exactly this with `:enter` pseudo class https://github.com/jonathantneal/postcss-pseudo-class-enter

**Comment by ai** [comment]
Done 904572b
