### ISSUE TITLE
Using focus-visible instead of focus

### ISSUE THREAD

**Issue by dreit-p** [postcss/postcss-focus#10]
If you use focus wherever you use hover, then the hover state seems to freeze after clicking. And just for keyboard accessibility you should use focus-visible. Can you change the default action or let it adjust yourself to set your own focus type?

**Comment by ai** [comment]
Good idea. Let's add an option (since `:focus-visible` is still not 100% supported). Please, send PR.

**Comment by ai** [comment]
Maybe we should just move to :focus-visible (in a major release) and have an option to switch to :focus?

Seems like :focus-visible is working everywhere.
