### ISSUE TITLE
Option to apply default styles

### ISSUE THREAD

**Issue by niksy** [postcss/postcss-focus#2]
If you want to apply `:hover` styles to `:focus` styles, I think it’s reasonable to think that you want to remove default outline on focus with `outline:0;`. Therefore, maybe it would be nice to have some initial styling applied?

**Comment by ai** [comment]
It is difficult to find best place to insert this `outline:0;`. Some components are independent, so be can’t use `*:focus {}`. Some times user will concat CSS files after PostCSS, so we can’t put `*:focus {}` in every file.

Anyway it is just a one line of code.

But maybe we can put this outline cleaner to plugin example? Do you want to send PR?

**Comment by niksy** [comment]
I was think of putting outline cleaning only to transformed `:hover` styles, so I suppose it won’t affect other selectors which only use `:focus` styles, only those with `:hover`. But I see your reasoning of focusing to one thing and one thing only.

As for outline cleaner, you mean creating another plugin, or just a option for this plugin?

**Comment by ai** [comment]
Hm. Good way. But I think it will make this plugin to complicated. Just one `*:focus {}` is better for many users. Maybe we should create a separated plugin for users who want it.

**Comment by ai** [comment]
Yeap, I think `*:focus { outline: 0 }` is a better way

**Comment by ai** [comment]
I just add it to example c1a0e80
